# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.3
    hooks:
      - id: go-vet

  - repo: https://github.com/Drafteame/pre-commit-golang
    rev: 0.10.1
    hooks:
      - id: go-mod-tidy
      - id: goimports-reviser
        args: ["-excludes=bin,node_modules,tmp,.git"]
      - id: revive
        args: ["-config=revive.toml", "-formatter=friendly"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.16.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/Drafteame/json-keys-diff-hook
    rev: v0.0.4
    hooks:
      - id: jkdiff-folder
        args: [ "--match=ejson$" ]

  - repo: https://github.com/Drafteame/ejson-hooks
    rev: 0.0.6
    hooks:
      - id: encrypt
