ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 0
exclude = ["scripts/...", "migrations/...", ".nix/..."]


[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.range]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unreachable-code]
[rule.redefines-builtin-id]
[rule.time-equal]
[rule.unnecessary-stmt]
[rule.range-val-in-closure]
[rule.range-val-address]
[rule.empty-lines]
[rule.unhandled-error]
[rule.early-return]
[rule.unconditional-recursion]
[rule.use-any]
[rule.datarace]